name: Dart

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{ secrets.COMMIT_SMARTVIEW }}
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    #container:
    #  image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.x'
          channel: 'dev'
          
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email dkao1222@gmail.com
          git config --global user.name dkao1222
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.COMMIT_SMARTVIEW}}@github.com/dkao1222/SmartView.Report.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
